"use client";

import { useState, useEffect } from "react";
import { runAudit, AuditInput } from "../lib/audit-engine"; 
import { supabase } from "../lib/supabase"; 

interface AuditResult {
  recommendedPlan: string;
  savings: number;
  annualSavings: number;
  aiSummary: string;
  reason: string;
}

export default function AuditPage() {
  const [formData, setFormData] = useState<AuditInput>({
    toolName: "Cursor",
    plan: "Business",
    seats: 1,
    monthlySpend: 40,
    useCase: "coding",
  });

  const [result, setResult] = useState<AuditResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [email, setEmail] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  // Persistence logic: Load from local storage
  useEffect(() => {
    const savedData = localStorage.getItem("auditFormData");
    if (savedData) {
      setFormData(JSON.parse(savedData));
    }
  }, []);

  // Save to local storage on change
  useEffect(() => {
    localStorage.setItem("auditFormData", JSON.stringify(formData));
  }, [formData]);

  const handleAudit = () => {
    setLoading(true);
    setTimeout(() => {
      const auditResult = runAudit(formData);
      setResult(auditResult as AuditResult);
      setLoading(false);
    }, 800);
  };

  const handleLeadCapture = async () => {
    if (!email || !email.includes("@")) {
      return alert("Please enter a valid work email");
    }
    if (!result) return;

    setIsSaving(true);
    try {
      // NOTE: We don't manually send 'id' because Supabase uses UUID type.
      // We use .select() to get the generated ID back from the database.
      const { data, error } = await supabase
        .from("leads")
        .insert([
          { 
            email: email, 
            tool_name: formData.toolName, 
            savings: result.savings,
            annual_savings: result.annualSavings,
            recommended_plan: result.recommendedPlan,
            reason: result.reason,
            use_case: formData.useCase
          }
        ])
        .select(); 

      if (error) throw error;

      if (data && data.length > 0) {
        alert("Success! Your audit report has been saved.");
        // Redirect using the UUID generated by Supabase
        window.location.href = `/audit/${data[0].id}`;
      }
    } catch (err) {
      console.error("Error saving lead:", err);
      alert("Database Error: Ensure your Supabase column names match exactly.");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <main className="min-h-screen bg-[#f8fafc] py-16 px-4 font-sans text-slate-900">
      <div className="max-w-2xl mx-auto">
        <div className="text-center mb-10">
          <div className="inline-block bg-blue-50 text-blue-700 text-xs font-bold px-3 py-1 rounded-full mb-4 border border-blue-100 uppercase tracking-widest">
            ✨ AI-Powered Optimization
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">
            AI <span className="text-blue-600">Spend</span> Auditor
          </h1>
          <p className="mt-4 text-lg text-slate-600">
            Optimize your SaaS overhead with automated financial auditing.
          </p>
        </div>

        <div className="bg-white border border-slate-200 rounded-2xl shadow-xl overflow-hidden">
          <div className="p-8">
            <div className="grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8">
              <div className="sm:col-span-2">
                <label className="block text-sm font-semibold text-slate-700 mb-2">AI Tool Provider</label>
                <select 
                  className="w-full bg-slate-50 border border-slate-300 rounded-lg p-3 outline-none focus:ring-2 focus:ring-blue-500"
                  value={formData.toolName}
                  onChange={(e) => setFormData({...formData, toolName: e.target.value})}
                >
                  <option value="Cursor">Cursor AI</option>
                  <option value="GitHub Copilot">GitHub Copilot</option>
                  <option value="ChatGPT">OpenAI (ChatGPT)</option>
                  <option value="Claude">Anthropic (Claude)</option>
                  <option value="Gemini">Google Gemini</option>
                  <option value="Windsurf">Windsurf</option>
                </select>
              </div>

              <div className="sm:col-span-2">
                <label className="block text-sm font-semibold text-slate-700 mb-2">Primary Use Case</label>
                <select 
                  className="w-full bg-slate-50 border border-slate-300 rounded-lg p-3 outline-none focus:ring-2 focus:ring-blue-500"
                  value={formData.useCase}
                  onChange={(e) => setFormData({...formData, useCase: e.target.value})}
                >
                  <option value="coding">Coding</option>
                  <option value="writing">Writing</option>
                  <option value="data">Data / Research</option>
                  <option value="mixed">Mixed</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">Active Seats</label>
                <input 
                  type="number" 
                  className="w-full bg-slate-50 border border-slate-300 rounded-lg p-3 outline-none focus:ring-2 focus:ring-blue-500"
                  value={formData.seats}
                  onChange={(e) => setFormData({...formData, seats: parseInt(e.target.value) || 0})}
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">Monthly Spend ($)</label>
                <input 
                  type="number" 
                  className="w-full bg-slate-50 border border-slate-300 rounded-lg p-3 outline-none focus:ring-2 focus:ring-blue-500"
                  value={formData.monthlySpend}
                  onChange={(e) => setFormData({...formData, monthlySpend: parseInt(e.target.value) || 0})}
                />
              </div>
            </div>

            <button 
              onClick={handleAudit}
              disabled={loading}
              className="mt-8 w-full bg-slate-900 text-white font-bold py-4 px-6 rounded-lg hover:bg-slate-800 transition-all shadow-lg flex items-center justify-center gap-2"
            >
              {loading ? "Analyzing..." : "Generate Optimization Report"}
            </button>
          </div>

          {result && !loading && (
            <div className="border-t border-slate-100 bg-slate-50 p-8 animate-in fade-in slide-in-from-bottom-4">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold text-slate-800">📊 Audit Summary</h2>
                <span className="bg-blue-100 text-blue-700 text-xs font-bold px-3 py-1 rounded-full uppercase">Verified Analysis</span>
              </div>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="bg-white p-4 rounded-xl border border-slate-200">
                  <p className="text-xs text-slate-500 font-bold uppercase tracking-wider">Recommended Plan</p>
                  <p className="text-xl font-bold text-blue-600">{result.recommendedPlan}</p>
                </div>
                <div className="bg-white p-4 rounded-xl border border-slate-200">
                  <p className="text-xs text-slate-500 font-bold uppercase tracking-wider">Monthly Savings</p>
                  <p className="text-xl font-bold text-green-600">${result.savings}/mo</p>
                </div>
              </div>

              <div className="mt-4 p-4 bg-white rounded-xl border border-slate-200 text-sm italic text-slate-600">
                <strong>Reason:</strong> {result.reason}
              </div>

              {result.savings >= 500 && (
                <div className="mt-6 p-6 border-2 border-blue-500 bg-blue-50 rounded-2xl">
                  <h3 className="text-lg font-bold text-blue-900">🚀 Massive Savings Found!</h3>
                  <p className="text-sm text-blue-800 mb-4">Book a consultation with Credex to access these institutional discounts.</p>
                  <button className="w-full bg-blue-600 text-white font-bold py-3 rounded-lg">Book Consultation</button>
                </div>
              )}

              <div className="mt-8 pt-8 border-t border-slate-200">
                <h3 className="text-sm font-bold text-slate-800 mb-3">Save and share this report</h3>
                <div className="flex flex-col sm:flex-row gap-3">
                  <input 
                    type="email" 
                    placeholder="Enter your work email"
                    className="flex-1 bg-white border border-slate-300 rounded-lg p-3 text-sm outline-none focus:ring-2 focus:ring-blue-500"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                  />
                  <button 
                    onClick={handleLeadCapture} 
                    disabled={isSaving} 
                    className="bg-blue-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-blue-700 transition-all disabled:bg-blue-400"
                  >
                    {isSaving ? "Saving..." : "Email & Share Report"}
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}